name: auto-generate-gitbook 
on: 
    push: 
        branches: 
            - main

jobs:
    main-to-gh-pages: 
        runs-on: ubuntu-latest

        steps: 
            - name: checkout main 
              uses: actions/checkout@v3 
              with: 
                ref: main

            - name: install nodejs 
              uses: actions/setup-node@v3.5.1 

            - name: configue gitbook 
              run: | 
                npm install gitbook-cli 
                gitbook install 
                npm install -g gitbook-summary 

            - name: generate _book folder
              run: | 
                book sm 
                gitbook build 
                cp SUMMARY.md _book 

            - name: push _book to branch gh-pages 
              env:
                TOKEN: ${{ secrets.TOKEN }}
                REF: github.com/${{github.repository}}
                MYEMAIL: brofu.talk@gmail.com
                MYNAME: ${{github.repository_owner}} 
              run: | 
                cd _book 
                git config --global user.email "${MYEMAIL}" 
                git config --global user.name "${MYNAME}" 
                git init 
                git remote add origin https://${REF} 
                git add . 
                git commit -m "Build pages. TODO: get commit info from main branch" 
                git branch -M main 
                git push --force --quiet "https://${TOKEN}@${REF}" main:gh-pages
